---
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    user:
      description: Selected User
      in: path
      name: user
      required: true
      schema:
        type: string
    game:
      description: Selected Game
      in: path
      name: game
      required: true
      schema:
        type: string
    gametype:
      description: Selected GameType
      in: path
      name: game
      required: true
      schema:
        type: string
  schemas:
    User:
      properties:
        id:
          description: User id, unique
          type: number
          format: int
        name:
          description: User name, unique
          type: string
        password:
          description: User password
          type: string
      required:
      - id
      - name
      - password
      type: object
    Game:
      properties:
        id:
          description: Game id, unique
          type: number
          format: int
        type:
          description: Game type
          type: number
          format: int
      required:
      - id
      - type
      type: object
    GameType:
      properties:
        id:
          description: GameType id, unique
          type: number
          format: int
        name:
          description: Game name, unique
          type: string
      required:
      - id
      - name
      type: object
  securitySchemes:
info:
  title: PWP BoardGame
  version: 0.0.1
  description: |
    This is an API used in the Programmable Web Project course.
    It stores data about games and the users who have played them.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: realaddress@email.net
    name: Boardgame group
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /users/:
    get:
      description: Get a list of all users. User passwords not included
      responses:
        '200':
          content:
            application/vnd.mason+json:
              example:
                '@controls':
                  boardgame:add-user:
                    encoding: json
                    href: /api/users/
                    method: POST
                    schema:
                      properties:
                        name:
                          maxLength: 64
                          minLength: 1
                          type: string
                        password:
                          type: string
                      required:
                      - name
                      - password
                      type: object
                  boardgame:games-all:
                    href: /api/games/
                    method: GET
                  boardgame:gametypes-all:
                    href: /api/game_types/
                    method: GET
                '@namespaces':
                  boardgame:
                    name: /boardgame/
                items:
                - '@controls':
                    self:
                      href: /api/users/user1
                  name: user1
                - '@controls':
                    self:
                      href: /api/users/user2
                  name: user2
                - '@controls':
                    self:
                      href: /api/users/user3
                  name: user3
    post:
  /users/{user}/:
    get:
    put:
    delete:
  /games/:
    get:
      description: Get a list of all games
      responses:
        '200':
          content:
            application/vnd.mason+json:
              example:
                '@controls':
                  boardgame:add-game:
                    encoding: json
                    href: /api/games/
                    method: POST
                    schema:
                      properties:
                        type:
                          type: string
                        user:
                          type: string
                      required:
                      - type
                      - user
                      type: object
                  boardgame:gametypes-all:
                    href: /api/game_types/
                    method: GET
                  boardgame:get-random:
                    href: /api/games/random/tictactoe
                  boardgame:users-all:
                    href: /api/users/
                    method: GET
                '@namespaces':
                  boardgame:
                    name: /boardgame/
                items:
                - '@controls':
                    self:
                      href: /api/games/15bd5a922e1b48ef9411b0d357660b73
                  currentPlayer: user1
                  id: 15bd5a922e1b48ef9411b0d357660b73
                  result: -1
                  state: 1---------
                  type: tictactoe
    post:
  /games/{game}/:
    get:
      description: Get information about a game instance
      responses:
        '200':
          content:
            application/vnd.mason+json:
              example:
                '@controls':
                  boardgame:delete:
                    href: /api/games/15bd5a922e1b48ef9411b0d357660b73
                    method: DELETE
                  boardgame:games-all:
                    href: /api/games/
                    method: GET
                  boardgame:join-game:
                    href: /api/games/15bd5a922e1b48ef9411b0d357660b73/join
                    method: POST
                  boardgame:make-move:
                    encoding: json
                    href: /api/games/15bd5a922e1b48ef9411b0d357660b73/moves
                    method: POST
                    schema:
                      properties:
                        moveTime:
                          type: integer
                      required:
                      - move
                      - moveTime
                      type: object
                  edit:
                    encoding: json
                    href: /api/games/15bd5a922e1b48ef9411b0d357660b73
                    method: PUT
                    schema:
                      properties:
                        currentPlayer:
        '404':
          description: Game instance not found
    put:
    delete:
  /games/{game}/moves/:
    get:
      description: get the move history of a given game instance
      responses:
        '200':
          content:
            application/vnd.mason+json:
              example:
                '@controls':
                  up:
                    href: /api/games/15bd5a922e1b48ef9411b0d357660b73
                moveHistory: None
        '404':
          description: Game instance not found
    post:
  /games/{game}/join/:
    post:
  /games/random/{game_type}/:
    get:
  /game_types/:
    get:
    post:
  /game_types/{game_type}/:
    get:
    put:
    delete:
